"""Generate the operator registry, the builder API and the reference docs.

Everything this module writes is derived from a single introspection pass over
the installed SNAP, and everything it writes is committed to the repository:

``snap_ops/operators.json``
    The full 439-operator snapshot.  Validation and codegen read this, so
    neither needs the JVM.
``snap_ops/op_funcs.py``
    Typed builder methods for the SAR-relevant operators.
``docs/operators.md``
    Human-readable parameter reference.

Run it with ``radar-snap gen-registry`` after upgrading SNAP.
"""

from __future__ import annotations

import json
import keyword
import math
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

from radar_snap_lib.snap_ops.registry import (
    REGISTRY_PATH,
    OperatorSpec,
    ParamSpec,
    Registry,
    introspect_all,
    registry_to_json,
    snap_version,
)

__all__ = [
    "generate_all",
    "method_name",
    "write_docs",
    "write_op_funcs",
    "write_registry",
]

OP_FUNCS_PATH = Path(__file__).with_name("op_funcs.py")

BANNER = "# Generated by `radar-snap gen-registry`. Do not edit by hand."

#: Splits camelCase and acronym boundaries: BandMaths -> Band_Maths,
#: SARSim -> SAR_Sim, while leaving TOPSAR intact.
_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def method_name(alias: str) -> str:
    """Python method name for a SNAP operator alias.

    ``Terrain-Correction`` -> ``terrain_correction``,
    ``TOPSAR-Split`` -> ``topsar_split``, ``BandMaths`` -> ``band_maths``.
    """
    name = re.sub(r"[-. ]+", "_", alias)
    name = _CAMEL_BOUNDARY.sub("_", name)
    return re.sub(r"_+", "_", name).lower().strip("_")


def arg_name(param: str) -> str:
    """Python argument name for a SNAP parameter name.

    Only ``RPCA-Change-Detection.lambda`` needs escaping, but the rule is
    general: a trailing underscore avoids the keyword clash.
    """
    return f"{param}_" if keyword.iskeyword(param) else param


def _literal(value: object) -> str:
    """Python source for a default value.

    This is where the old ``SnappyNodeCreator`` went wrong: it printed SNAP's
    raw metadata strings, producing ``demName=SRTM 3Sec`` instead of
    ``demName="SRTM 3Sec"`` and ``true`` instead of ``True``.

    ``repr`` covers every case except non-finite floats, whose reprs (``nan``,
    ``inf``) are not valid Python expressions.
    """
    if isinstance(value, float) and not math.isfinite(value):
        if math.isnan(value):
            return 'float("nan")'
        return 'float("inf")' if value > 0 else 'float("-inf")'
    if isinstance(value, tuple):
        return "(" + "".join(f"{_literal(item)}, " for item in value) + ")"
    return repr(value)


def _clean(text: str) -> str:
    """Collapse a SNAP description into a single safe docstring line."""
    return " ".join(text.split()).replace("\\", "/").replace('"""', "'''")


# --------------------------------------------------------------------------- #
# operators.json
# --------------------------------------------------------------------------- #


def write_registry(
    registry: Registry, *, path: Path = REGISTRY_PATH, version: str
) -> Path:
    """Write the operator snapshot as sorted, diff-friendly JSON."""
    document = registry_to_json(registry, version=version)
    # allow_nan=False keeps the snapshot standards-compliant: non-finite floats
    # are encoded as strings upstream, so reaching here means a real bug.
    path.write_text(
        json.dumps(
            document, indent=2, ensure_ascii=False, sort_keys=False, allow_nan=False
        )
        + "\n",
        encoding="utf-8",
    )
    return path


# --------------------------------------------------------------------------- #
# op_funcs.py
# --------------------------------------------------------------------------- #


def _signature_parts(spec: OperatorSpec) -> tuple[list[str], str, list[str]]:
    """Build the source arguments, the ``_add`` source expression, and the pops.

    Returns ``(positional_source_args, sources_expression, names_to_pop)``.
    """
    if spec.takes_source_array:
        return ["*sources: NodeRef"], "sources", ["sources"]

    named = [src for src in spec.sources if not src.is_array]
    if not named:
        return [], "()", []
    if len(named) == 1:
        return ["source: NodeRef"], "[source]", ["source"]

    args: list[str] = []
    pops: list[str] = []
    for index, src in enumerate(named):
        name = method_name(src.name) if index else "source"
        pops.append(name)
        args.append(
            f"{name}: NodeRef | None = None" if src.optional else f"{name}: NodeRef"
        )
    return args, "[" + ", ".join(pops) + "]", pops


def _param_args(spec: OperatorSpec) -> tuple[list[str], list[str]]:
    """Split parameters into required (positional) and optional (keyword-only)."""
    required: list[str] = []
    optional: list[str] = []
    for param in spec.params.values():
        annotation = param.python_type
        name = arg_name(param.name)
        if param.required:
            required.append(f"{name}: {annotation}")
        else:
            optional.append(f"{name}: {annotation} = {_literal(param.default)}")
    return required, optional


def _docstring(spec: OperatorSpec) -> list[str]:
    summary = _clean(spec.description or f"SNAP operator {spec.alias}.")
    if not summary.endswith("."):
        summary += "."

    # SNAP descriptions run to arbitrary length; wrap so the generated module
    # stays within the project's line limit.
    wrapped = textwrap.wrap(summary, width=72) or [summary]
    lines = [f'    """{wrapped[0]}']
    lines.extend(f"    {line}" for line in wrapped[1:])
    lines.append("")
    lines.append(f"    SNAP operator: ``{spec.alias}``")

    constrained = [p for p in spec.params.values() if p.value_set]
    if constrained:
        lines.append("")
        lines.append("    Constrained parameters:")
        for param in constrained:
            allowed = " | ".join(param.value_set)
            wrapped = textwrap.wrap(
                f"{param.name}: {allowed}",
                width=76,
                initial_indent="        ",
                subsequent_indent="            ",
            )
            lines.extend(wrapped)
    lines.append('    """')
    return lines


def _render_method(spec: OperatorSpec) -> str:
    source_args, sources_expr, source_pops = _signature_parts(spec)
    required, optional = _param_args(spec)

    args = ["self", *source_args, *required]
    if optional:
        if not any(a.startswith("*") for a in source_args):
            args.append("*")
        args.extend(optional)

    lines = [f"def {method_name(spec.alias)}("]
    lines.extend(f"    {arg}," for arg in args)
    lines.append(") -> NodeRef:")
    lines.extend(_docstring(spec))

    lines.append("    params = dict(locals())")
    for name in ("self", *source_pops):
        lines.append(f'    params.pop("{name}")')
    for param in spec.params.values():
        escaped = arg_name(param.name)
        if escaped != param.name:
            lines.append(f'    params["{param.name}"] = params.pop("{escaped}")')
    lines.append(f"    return self._add({spec.alias!r}, {sources_expr}, params)")

    return textwrap.indent("\n".join(lines), "    ")


def write_op_funcs(registry: Registry, *, path: Path = OP_FUNCS_PATH) -> Path:
    """Write the typed builder mixin for the SAR-relevant operators."""
    specs = [spec for spec in registry.values() if spec.is_sar]

    seen: dict[str, str] = {}
    for spec in specs:
        name = method_name(spec.alias)
        if name in seen:
            raise RuntimeError(
                f"Method name collision: {spec.alias!r} and {seen[name]!r} "
                f"both map to {name!r}"
            )
        seen[name] = spec.alias

    header = f'''{BANNER}
"""Typed builder methods for the SAR-relevant SNAP operators.

{len(specs)} of the {len(registry)} operators SNAP exposes get a method here: the
radar, core-GPF, polarimetry, InSAR and DEM ones. The rest are optical and stay
reachable through :meth:`Graph.node`.

Every method appends a node and returns a :class:`NodeRef`; nothing executes
until :meth:`Graph.run`. Parameters SNAP marks as required are positional, the
rest are keyword-only with SNAP's own default.
"""

from __future__ import annotations

from typing import Any

from radar_snap_lib.snap_ops.nodes import NodeRef

__all__ = ["OpFuncs"]


class OpFuncs:
    """Mixin adding one builder method per SAR-relevant SNAP operator."""

    _add: Any
'''

    body = "\n\n".join(_render_method(spec) for spec in specs)
    path.write_text(f"{header}\n{body}\n", encoding="utf-8")
    _format(path)
    return path


def _format(path: Path) -> None:
    """Run ruff over a generated file so its output is stable and lint-clean."""
    ruff = shutil.which("ruff")
    if ruff is None:  # pragma: no cover - ruff is a dev dependency
        return
    subprocess.run([ruff, "check", "--fix", "--quiet", str(path)], check=False)
    subprocess.run([ruff, "format", "--quiet", str(path)], check=False)


# --------------------------------------------------------------------------- #
# docs/operators.md
# --------------------------------------------------------------------------- #


def _docs_root() -> Path:
    return Path(__file__).resolve().parents[3] / "docs"


def _param_row(param: ParamSpec) -> str:
    default = "" if param.default is None else f"`{param.default}`"
    values = " / ".join(f"`{v}`" for v in param.value_set) if param.value_set else ""
    flags = []
    if param.required:
        flags.append("**required**")
    if param.alias:
        flags.append(f"alias `{param.alias}`")
    notes = ", ".join(flags)
    description = _clean(param.description or "")
    detail = " ".join(part for part in (values, notes, description) if part)
    return f"| `{param.name}` | `{param.type}` | {default} | {detail} |"


def _operator_section(spec: OperatorSpec) -> str:
    lines = [f"### `{spec.alias}`", ""]
    if spec.description:
        lines.extend([_clean(spec.description), ""])
    lines.append(f"- Class: `{spec.cls}`")
    lines.append(
        f"- Builder: `Graph.{method_name(spec.alias)}()`"
        if spec.is_sar
        else f'- Builder: `Graph.node("{spec.alias}", ...)`'
    )

    if spec.takes_source_array:
        lines.append("- Sources: any number (`sourceProducts`)")
    elif spec.sources:
        names = ", ".join(
            f"`{s.name}`{' (optional)' if s.optional else ''}" for s in spec.sources
        )
        lines.append(f"- Sources: {names}")
    else:
        lines.append("- Sources: none")
    lines.append("")

    if spec.params:
        lines.append("| Parameter | Type | Default | Notes |")
        lines.append("| --- | --- | --- | --- |")
        lines.extend(_param_row(param) for param in spec.params.values())
    else:
        lines.append("_No parameters._")
    lines.append("")
    return "\n".join(lines)


def write_docs(registry: Registry, *, path: Path | None = None, version: str) -> Path:
    """Write the Markdown operator reference."""
    path = path or (_docs_root() / "operators.md")
    path.parent.mkdir(parents=True, exist_ok=True)

    sar = [spec for spec in registry.values() if spec.is_sar]
    other = [spec for spec in registry.values() if not spec.is_sar]
    total_params = sum(len(spec.params) for spec in registry.values())

    lines = [
        "<!-- Generated by `radar-snap gen-registry`. Do not edit by hand. -->",
        "",
        "# SNAP Operator Reference",
        "",
        f"SNAP {version} - {len(registry)} operators, {total_params} parameters.",
        "",
        f"{len(sar)} operators have a generated builder method on `Graph`; the "
        f"remaining {len(other)} are reachable via `Graph.node(alias, ...)`.",
        "",
        "## SAR, core GPF, polarimetry, InSAR and DEM operators",
        "",
    ]
    lines.extend(_operator_section(spec) for spec in sar)
    lines.extend(["## Remaining operators", ""])
    lines.extend(_operator_section(spec) for spec in other)

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# --------------------------------------------------------------------------- #


def generate_all() -> dict[str, Path]:
    """Introspect SNAP and regenerate every derived artifact."""
    version = snap_version()
    registry = introspect_all()
    return {
        "registry": write_registry(registry, version=version),
        "op_funcs": write_op_funcs(registry),
        "docs": write_docs(registry, version=version),
    }
