"""Locate the external ESA SNAP (``esa_snappy``) environment.

``esa_snappy`` cannot be installed from PyPI -- it is generated by SNAP's
``snappy-conf`` into a dedicated virtual environment.  This module resolves the
path to that environment and makes its ``site-packages`` importable.

Resolution order (first hit wins):

1. environment variable ``ESA_SNAPPY_VENV``
2. ``.env`` file next to ``pyproject.toml`` (key ``ESA_SNAPPY_VENV``)
3. ``[tool.radar-snap-lib] esa-snappy-venv`` in ``pyproject.toml``
"""

from __future__ import annotations

import os
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ENV_VAR = "ESA_SNAPPY_VENV"
_TOOL_TABLE = "radar-snap-lib"
_TOOL_KEY = "esa-snappy-venv"
EDL_TOKEN_VAR = "EARTHDATA_TOKEN"
EDL_USERNAME_VAR = "EARTHDATA_USERNAME"
EDL_PASSWORD_VAR = "EARTHDATA_PASSWORD"

__all__ = [
    "EDL_PASSWORD_VAR",
    "EDL_TOKEN_VAR",
    "EDL_USERNAME_VAR",
    "ENV_VAR",
    "EarthdataCredentials",
    "earthdata_credentials",
    "ensure_esa_snappy",
    "env_value",
    "snappy_site_packages",
    "snappy_venv_path",
]


def _project_root() -> Path | None:
    """Nearest ancestor directory containing a ``pyproject.toml``."""
    for candidate in (Path.cwd(), Path(__file__).resolve().parent):
        for directory in (candidate, *candidate.parents):
            if (directory / "pyproject.toml").is_file():
                return directory
    return None


def _from_env(key: str) -> str | None:
    return os.environ.get(key) or None


def _from_dotenv(root: Path, key: str) -> str | None:
    dotenv = root / ".env"
    if not dotenv.is_file():
        return None
    for raw in dotenv.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        if name.strip().removeprefix("export ").strip() != key:
            continue
        return value.strip().strip("'\"") or None
    return None


def env_value(key: str) -> str | None:
    """Resolve a setting from the environment, then the project's ``.env``.

    Deliberately does not consult ``pyproject.toml`` -- that file is committed,
    and this is the path credentials travel.
    """
    value = _from_env(key)
    if value is not None:
        return value
    root = _project_root()
    return None if root is None else _from_dotenv(root, key)


def _from_pyproject(root: Path) -> str | None:
    data = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    value = data.get("tool", {}).get(_TOOL_TABLE, {}).get(_TOOL_KEY)
    return value or None


def snappy_venv_path() -> Path | None:
    """Return the configured ``esa_snappy`` venv, or ``None`` if unset."""
    root = _project_root()
    value = _from_env(ENV_VAR)
    if value is None and root is not None:
        value = _from_dotenv(root, ENV_VAR) or _from_pyproject(root)
    if value is None:
        return None
    path = Path(os.path.expandvars(value)).expanduser()
    if not path.is_absolute() and root is not None:
        path = root / path
    return path.resolve()


def snappy_site_packages() -> Path:
    """Return the ``site-packages`` directory of the configured venv."""
    venv = snappy_venv_path()
    if venv is None:
        raise RuntimeError(
            f"No esa_snappy environment configured. Set {ENV_VAR} in your "
            f"environment or .env file, or [tool.{_TOOL_TABLE}] {_TOOL_KEY} "
            "in pyproject.toml."
        )
    if not venv.is_dir():
        raise RuntimeError(f"Configured esa_snappy venv does not exist: {venv}")

    if os.name == "nt":
        candidates = [venv / "Lib" / "site-packages"]
    else:
        version = f"python{sys.version_info.major}.{sys.version_info.minor}"
        candidates = [venv / "lib" / version / "site-packages"]
        candidates += sorted(venv.glob("lib/python3.*/site-packages"))

    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    raise RuntimeError(f"No site-packages found in esa_snappy venv: {venv}")


def ensure_esa_snappy() -> Path:
    """Put the ``esa_snappy`` venv on ``sys.path``. Idempotent.

    Appended, never prepended.  The SNAP venv ships ``requests``, ``urllib3``,
    ``certifi`` and friends alongside ``esa_snappy``; prepending would let those
    shadow the project's own locked versions, which ``asf_search`` depends on.
    ``esa_snappy`` and ``jpy`` exist nowhere else, so appending still finds them.

    Returns the ``site-packages`` directory that was added.
    """
    site_packages = snappy_site_packages()
    entry = str(site_packages)
    if entry not in sys.path:
        sys.path.append(entry)
    return site_packages


@dataclass(frozen=True)
class EarthdataCredentials:
    """NASA Earthdata Login credentials, token preferred over username/password."""

    token: str | None = None
    username: str | None = None
    password: str | None = None


def earthdata_credentials() -> EarthdataCredentials | None:
    """Resolve Earthdata Login credentials, or ``None`` if none are configured.

    A token wins over a username/password pair.  A username without a password
    counts as unconfigured -- half a credential is not a credential.
    """
    token = env_value(EDL_TOKEN_VAR)
    if token is not None:
        return EarthdataCredentials(token=token)
    username = env_value(EDL_USERNAME_VAR)
    password = env_value(EDL_PASSWORD_VAR)
    if username is not None and password is not None:
        return EarthdataCredentials(username=username, password=password)
    return None
