"""Locate the external ESA SNAP (``esa_snappy``) environment.

``esa_snappy`` cannot be installed from PyPI -- it is generated by SNAP's
``snappy-conf`` into a dedicated virtual environment.  This module resolves the
path to that environment and makes its ``site-packages`` importable.

Resolution order (first hit wins):

1. environment variable ``ESA_SNAPPY_VENV``
2. ``.env`` file next to ``pyproject.toml`` (key ``ESA_SNAPPY_VENV``)
3. ``[tool.radar-snap-lib] esa-snappy-venv`` in ``pyproject.toml``
"""

from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path

ENV_VAR = "ESA_SNAPPY_VENV"
_TOOL_TABLE = "radar-snap-lib"
_TOOL_KEY = "esa-snappy-venv"


def _project_root() -> Path | None:
    """Nearest ancestor directory containing a ``pyproject.toml``."""
    for candidate in (Path.cwd(), Path(__file__).resolve().parent):
        for directory in (candidate, *candidate.parents):
            if (directory / "pyproject.toml").is_file():
                return directory
    return None


def _from_env() -> str | None:
    return os.environ.get(ENV_VAR) or None


def _from_dotenv(root: Path) -> str | None:
    dotenv = root / ".env"
    if not dotenv.is_file():
        return None
    for raw in dotenv.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        if key.strip().removeprefix("export ").strip() != ENV_VAR:
            continue
        return value.strip().strip("'\"") or None
    return None


def _from_pyproject(root: Path) -> str | None:
    data = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    value = data.get("tool", {}).get(_TOOL_TABLE, {}).get(_TOOL_KEY)
    return value or None


def snappy_venv_path() -> Path | None:
    """Return the configured ``esa_snappy`` venv, or ``None`` if unset."""
    root = _project_root()
    value = _from_env()
    if value is None and root is not None:
        value = _from_dotenv(root) or _from_pyproject(root)
    if value is None:
        return None
    path = Path(os.path.expandvars(value)).expanduser()
    if not path.is_absolute() and root is not None:
        path = root / path
    return path.resolve()


def snappy_site_packages() -> Path:
    """Return the ``site-packages`` directory of the configured venv."""
    venv = snappy_venv_path()
    if venv is None:
        raise RuntimeError(
            f"No esa_snappy environment configured. Set {ENV_VAR} in your "
            f"environment or .env file, or [tool.{_TOOL_TABLE}] {_TOOL_KEY} "
            "in pyproject.toml."
        )
    if not venv.is_dir():
        raise RuntimeError(f"Configured esa_snappy venv does not exist: {venv}")

    if os.name == "nt":
        candidates = [venv / "Lib" / "site-packages"]
    else:
        version = f"python{sys.version_info.major}.{sys.version_info.minor}"
        candidates = [venv / "lib" / version / "site-packages"]
        candidates += sorted(venv.glob("lib/python3.*/site-packages"))

    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    raise RuntimeError(f"No site-packages found in esa_snappy venv: {venv}")


def ensure_esa_snappy() -> Path:
    """Put the ``esa_snappy`` venv on ``sys.path``. Idempotent.

    Returns the ``site-packages`` directory that was added.
    """
    site_packages = snappy_site_packages()
    entry = str(site_packages)
    if entry not in sys.path:
        sys.path.insert(0, entry)
    return site_packages
